apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pulsecart
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: staging
            namespace: pulsecart-staging
          - env: production
            namespace: pulsecart-production
  template:
    metadata:
      name: 'pulsecart-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Jashwanth248/Devops-.git
        targetRevision: main
        path: platform/helm/pulsecart-service
        helm:
          valueFiles:
            - '../../../environments/{{env}}/gateway-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
