apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-secure-containers
spec:
  validationFailureAction: Audit
  rules:
    - name: require-non-root
      match:
        any:
          - resources:
              kinds: [Pod]
      validate:
        message: Containers must run as non-root and disallow privilege escalation.
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
